// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_github.Data;

#nullable disable

namespace backend_github.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251102014407_UsuariosEstaticos")]
    partial class UsuariosEstaticos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("backend_github.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "admin@historia.com",
                            Nombre = "Administrador",
                            PasswordHash = "5ac0852e770506dcd80f1a36d20ba7878bf82244b836d9324593bd14bc56dcb5"
                        },
                        new
                        {
                            Id = 2,
                            Correo = "invitado@historia.com",
                            Nombre = "Invitado",
                            PasswordHash = "06eda208dfb875dd849366a325a9e71e51df058731bf60a3b37f85ec6df12992"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
